# Generated by Django 5.2 on 2025-04-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistQuote',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='nome programmatico')),
                ('title', models.CharField(max_length=128, verbose_name='titolo')),
                ('body', models.TextField()),
                ('main_avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='avatar artista')),
                ('sub_avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='avatar opera')),
                ('artist', models.CharField(max_length=64, verbose_name='artista')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='nome programmatico')),
                ('title', models.CharField(max_length=128, verbose_name='titolo')),
                ('body', models.TextField()),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='avatar artista')),
                ('tags', models.CharField(max_length=256, verbose_name="tags separate da ','")),
            ],
        ),
    ]
